//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAPI
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Booking.
    /// </summary>
    // *** Start programmer edit section *** (Booking CustomAttributes)

    // *** End programmer edit section *** (Booking CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookingE", new string[] {
            "GuestName as \'Guest name\'",
            "CheckIn as \'Check in\'",
            "CheckOut as \'Check out\'",
            "Room"})]
    [View("BookingL", new string[] {
            "GuestName as \'Guest name\'",
            "CheckIn as \'Check in\'",
            "CheckOut as \'Check out\'",
            "Room",
            "Room.Price"})]
    public class Booking : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fCheckIn;

        private System.DateTime fCheckOut;

        private string fGuestName;

        private HAPI.Client fClient;

        private HAPI.Room fRoom;

        // *** Start programmer edit section *** (Booking CustomMembers)

        // *** End programmer edit section *** (Booking CustomMembers)


        /// <summary>
        /// CheckIn.
        /// </summary>
        // *** Start programmer edit section *** (Booking.CheckIn CustomAttributes)

        // *** End programmer edit section *** (Booking.CheckIn CustomAttributes)
        public virtual System.DateTime CheckIn
        {
            get
            {
                // *** Start programmer edit section *** (Booking.CheckIn Get start)

                // *** End programmer edit section *** (Booking.CheckIn Get start)
                System.DateTime result = this.fCheckIn;
                // *** Start programmer edit section *** (Booking.CheckIn Get end)

                // *** End programmer edit section *** (Booking.CheckIn Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Booking.CheckIn Set start)

                // *** End programmer edit section *** (Booking.CheckIn Set start)
                this.fCheckIn = value;
                // *** Start programmer edit section *** (Booking.CheckIn Set end)

                // *** End programmer edit section *** (Booking.CheckIn Set end)
            }
        }

        /// <summary>
        /// CheckOut.
        /// </summary>
        // *** Start programmer edit section *** (Booking.CheckOut CustomAttributes)

        // *** End programmer edit section *** (Booking.CheckOut CustomAttributes)
        public virtual System.DateTime CheckOut
        {
            get
            {
                // *** Start programmer edit section *** (Booking.CheckOut Get start)

                // *** End programmer edit section *** (Booking.CheckOut Get start)
                System.DateTime result = this.fCheckOut;
                // *** Start programmer edit section *** (Booking.CheckOut Get end)

                // *** End programmer edit section *** (Booking.CheckOut Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Booking.CheckOut Set start)

                // *** End programmer edit section *** (Booking.CheckOut Set start)
                this.fCheckOut = value;
                // *** Start programmer edit section *** (Booking.CheckOut Set end)

                // *** End programmer edit section *** (Booking.CheckOut Set end)
            }
        }

        /// <summary>
        /// GuestName.
        /// </summary>
        // *** Start programmer edit section *** (Booking.GuestName CustomAttributes)

        // *** End programmer edit section *** (Booking.GuestName CustomAttributes)
        [StrLen(255)]
        public virtual string GuestName
        {
            get
            {
                // *** Start programmer edit section *** (Booking.GuestName Get start)

                // *** End programmer edit section *** (Booking.GuestName Get start)
                string result = this.fGuestName;
                // *** Start programmer edit section *** (Booking.GuestName Get end)

                // *** End programmer edit section *** (Booking.GuestName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Booking.GuestName Set start)

                // *** End programmer edit section *** (Booking.GuestName Set start)
                this.fGuestName = value;
                // *** Start programmer edit section *** (Booking.GuestName Set end)

                // *** End programmer edit section *** (Booking.GuestName Set end)
            }
        }

        /// <summary>
        /// Booking.
        /// </summary>
        // *** Start programmer edit section *** (Booking.Client CustomAttributes)

        // *** End programmer edit section *** (Booking.Client CustomAttributes)
        [PropertyStorage(new string[] {
                "Client"})]
        [NotNull()]
        public virtual HAPI.Client Client
        {
            get
            {
                // *** Start programmer edit section *** (Booking.Client Get start)

                // *** End programmer edit section *** (Booking.Client Get start)
                HAPI.Client result = this.fClient;
                // *** Start programmer edit section *** (Booking.Client Get end)

                // *** End programmer edit section *** (Booking.Client Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Booking.Client Set start)

                // *** End programmer edit section *** (Booking.Client Set start)
                this.fClient = value;
                // *** Start programmer edit section *** (Booking.Client Set end)

                // *** End programmer edit section *** (Booking.Client Set end)
            }
        }

        /// <summary>
        /// Booking.
        /// </summary>
        // *** Start programmer edit section *** (Booking.Room CustomAttributes)

        // *** End programmer edit section *** (Booking.Room CustomAttributes)
        [PropertyStorage(new string[] {
                "Room"})]
        [NotNull()]
        public virtual HAPI.Room Room
        {
            get
            {
                // *** Start programmer edit section *** (Booking.Room Get start)

                // *** End programmer edit section *** (Booking.Room Get start)
                HAPI.Room result = this.fRoom;
                // *** Start programmer edit section *** (Booking.Room Get end)

                // *** End programmer edit section *** (Booking.Room Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Booking.Room Set start)

                // *** End programmer edit section *** (Booking.Room Set start)
                this.fRoom = value;
                // *** Start programmer edit section *** (Booking.Room Set end)

                // *** End programmer edit section *** (Booking.Room Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "BookingE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookingE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookingE", typeof(HAPI.Booking));
                }
            }

            /// <summary>
            /// "BookingL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookingL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookingL", typeof(HAPI.Booking));
                }
            }
        }
    }
}

