//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAPI
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Client.
    /// </summary>
    // *** Start programmer edit section *** (Client CustomAttributes)

    // *** End programmer edit section *** (Client CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ClientE", new string[] {
            "FirstName as \'First name\'",
            "LastName as \'Last name\'",
            "PhoneNumber as \'Phone number\'",
            "PassportNumber as \'Passport number\'",
            "Email as \'Email\'"})]
    [View("ClientL", new string[] {
            "FirstName as \'First name\'",
            "LastName as \'Last name\'",
            "PhoneNumber as \'Phone number\'",
            "PassportNumber as \'Passport number\'",
            "Email as \'Email\'"})]
    public class Client : ICSSoft.STORMNET.DataObject
    {

        private string fEmail;

        private string fFirstName;

        private string fLastName;

        private string fPassportNumber;

        private string fPhoneNumber;

        // *** Start programmer edit section *** (Client CustomMembers)

        // *** End programmer edit section *** (Client CustomMembers)


        /// <summary>
        /// Email.
        /// </summary>
        // *** Start programmer edit section *** (Client.Email CustomAttributes)

        // *** End programmer edit section *** (Client.Email CustomAttributes)
        [StrLen(255)]
        public virtual string Email
        {
            get
            {
                // *** Start programmer edit section *** (Client.Email Get start)

                // *** End programmer edit section *** (Client.Email Get start)
                string result = this.fEmail;
                // *** Start programmer edit section *** (Client.Email Get end)

                // *** End programmer edit section *** (Client.Email Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.Email Set start)

                // *** End programmer edit section *** (Client.Email Set start)
                this.fEmail = value;
                // *** Start programmer edit section *** (Client.Email Set end)

                // *** End programmer edit section *** (Client.Email Set end)
            }
        }

        /// <summary>
        /// FirstName.
        /// </summary>
        // *** Start programmer edit section *** (Client.FirstName CustomAttributes)

        // *** End programmer edit section *** (Client.FirstName CustomAttributes)
        [StrLen(255)]
        public virtual string FirstName
        {
            get
            {
                // *** Start programmer edit section *** (Client.FirstName Get start)

                // *** End programmer edit section *** (Client.FirstName Get start)
                string result = this.fFirstName;
                // *** Start programmer edit section *** (Client.FirstName Get end)

                // *** End programmer edit section *** (Client.FirstName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.FirstName Set start)

                // *** End programmer edit section *** (Client.FirstName Set start)
                this.fFirstName = value;
                // *** Start programmer edit section *** (Client.FirstName Set end)

                // *** End programmer edit section *** (Client.FirstName Set end)
            }
        }

        /// <summary>
        /// LastName.
        /// </summary>
        // *** Start programmer edit section *** (Client.LastName CustomAttributes)

        // *** End programmer edit section *** (Client.LastName CustomAttributes)
        [StrLen(255)]
        public virtual string LastName
        {
            get
            {
                // *** Start programmer edit section *** (Client.LastName Get start)

                // *** End programmer edit section *** (Client.LastName Get start)
                string result = this.fLastName;
                // *** Start programmer edit section *** (Client.LastName Get end)

                // *** End programmer edit section *** (Client.LastName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.LastName Set start)

                // *** End programmer edit section *** (Client.LastName Set start)
                this.fLastName = value;
                // *** Start programmer edit section *** (Client.LastName Set end)

                // *** End programmer edit section *** (Client.LastName Set end)
            }
        }

        /// <summary>
        /// PassportNumber.
        /// </summary>
        // *** Start programmer edit section *** (Client.PassportNumber CustomAttributes)

        // *** End programmer edit section *** (Client.PassportNumber CustomAttributes)
        [StrLen(255)]
        public virtual string PassportNumber
        {
            get
            {
                // *** Start programmer edit section *** (Client.PassportNumber Get start)

                // *** End programmer edit section *** (Client.PassportNumber Get start)
                string result = this.fPassportNumber;
                // *** Start programmer edit section *** (Client.PassportNumber Get end)

                // *** End programmer edit section *** (Client.PassportNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.PassportNumber Set start)

                // *** End programmer edit section *** (Client.PassportNumber Set start)
                this.fPassportNumber = value;
                // *** Start programmer edit section *** (Client.PassportNumber Set end)

                // *** End programmer edit section *** (Client.PassportNumber Set end)
            }
        }

        /// <summary>
        /// PhoneNumber.
        /// </summary>
        // *** Start programmer edit section *** (Client.PhoneNumber CustomAttributes)

        // *** End programmer edit section *** (Client.PhoneNumber CustomAttributes)
        [StrLen(255)]
        public virtual string PhoneNumber
        {
            get
            {
                // *** Start programmer edit section *** (Client.PhoneNumber Get start)

                // *** End programmer edit section *** (Client.PhoneNumber Get start)
                string result = this.fPhoneNumber;
                // *** Start programmer edit section *** (Client.PhoneNumber Get end)

                // *** End programmer edit section *** (Client.PhoneNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Client.PhoneNumber Set start)

                // *** End programmer edit section *** (Client.PhoneNumber Set start)
                this.fPhoneNumber = value;
                // *** Start programmer edit section *** (Client.PhoneNumber Set end)

                // *** End programmer edit section *** (Client.PhoneNumber Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ClientE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientE", typeof(HAPI.Client));
                }
            }

            /// <summary>
            /// "ClientL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClientL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClientL", typeof(HAPI.Client));
                }
            }
        }
    }
}

