//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAPI
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Comfort level type.
    /// </summary>
    // *** Start programmer edit section *** (ComfortLevelType CustomAttributes)

    // *** End programmer edit section *** (ComfortLevelType CustomAttributes)
    public enum ComfortLevelType
    {

        // *** Start programmer edit section *** (ComfortLevelType.Standard CustomAttributes)

        // *** End programmer edit section *** (ComfortLevelType.Standard CustomAttributes)
        [Caption("Standard")]
        Standard,

        // *** Start programmer edit section *** (ComfortLevelType.Economy CustomAttributes)

        // *** End programmer edit section *** (ComfortLevelType.Economy CustomAttributes)
        [Caption("Economy")]
        Economy,

        // *** Start programmer edit section *** (ComfortLevelType.Luxury CustomAttributes)

        // *** End programmer edit section *** (ComfortLevelType.Luxury CustomAttributes)
        [Caption("Luxury")]
        Luxury,

        // *** Start programmer edit section *** (ComfortLevelType.PresidentialSuite CustomAttributes)

        // *** End programmer edit section *** (ComfortLevelType.PresidentialSuite CustomAttributes)
        [Caption("Presidential suite")]
        PresidentialSuite,
    }
}

