//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAPI
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    // *** Start programmer edit section *** (Room CustomAttributes)

    // *** End programmer edit section *** (Room CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RoomE", new string[] {
            "RoomNumber as \'Room number\'",
            "Price as \'Price\'",
            "RoomType as \'Room type\'"})]
    [View("RoomL", new string[] {
            "RoomNumber as \'Room number\'",
            "Price as \'Price\'",
            "RoomType as \'Room type\'"})]
    public class Room : ICSSoft.STORMNET.DataObject
    {

        private double fPrice;

        private int fRoomNumber;

        private HAPI.ComfortLevelType fRoomType;

        // *** Start programmer edit section *** (Room CustomMembers)

        // *** End programmer edit section *** (Room CustomMembers)


        /// <summary>
        /// Price.
        /// </summary>
        // *** Start programmer edit section *** (Room.Price CustomAttributes)

        // *** End programmer edit section *** (Room.Price CustomAttributes)
        public virtual double Price
        {
            get
            {
                // *** Start programmer edit section *** (Room.Price Get start)

                // *** End programmer edit section *** (Room.Price Get start)
                double result = this.fPrice;
                // *** Start programmer edit section *** (Room.Price Get end)

                // *** End programmer edit section *** (Room.Price Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Price Set start)

                // *** End programmer edit section *** (Room.Price Set start)
                this.fPrice = value;
                // *** Start programmer edit section *** (Room.Price Set end)

                // *** End programmer edit section *** (Room.Price Set end)
            }
        }

        /// <summary>
        /// RoomNumber.
        /// </summary>
        // *** Start programmer edit section *** (Room.RoomNumber CustomAttributes)

        // *** End programmer edit section *** (Room.RoomNumber CustomAttributes)
        public virtual int RoomNumber
        {
            get
            {
                // *** Start programmer edit section *** (Room.RoomNumber Get start)

                // *** End programmer edit section *** (Room.RoomNumber Get start)
                int result = this.fRoomNumber;
                // *** Start programmer edit section *** (Room.RoomNumber Get end)

                // *** End programmer edit section *** (Room.RoomNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.RoomNumber Set start)

                // *** End programmer edit section *** (Room.RoomNumber Set start)
                this.fRoomNumber = value;
                // *** Start programmer edit section *** (Room.RoomNumber Set end)

                // *** End programmer edit section *** (Room.RoomNumber Set end)
            }
        }

        /// <summary>
        /// RoomType.
        /// </summary>
        // *** Start programmer edit section *** (Room.RoomType CustomAttributes)

        // *** End programmer edit section *** (Room.RoomType CustomAttributes)
        public virtual HAPI.ComfortLevelType RoomType
        {
            get
            {
                // *** Start programmer edit section *** (Room.RoomType Get start)

                // *** End programmer edit section *** (Room.RoomType Get start)
                HAPI.ComfortLevelType result = this.fRoomType;
                // *** Start programmer edit section *** (Room.RoomType Get end)

                // *** End programmer edit section *** (Room.RoomType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.RoomType Set start)

                // *** End programmer edit section *** (Room.RoomType Set start)
                this.fRoomType = value;
                // *** Start programmer edit section *** (Room.RoomType Set end)

                // *** End programmer edit section *** (Room.RoomType Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "RoomE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomE", typeof(HAPI.Room));
                }
            }

            /// <summary>
            /// "RoomL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RoomL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RoomL", typeof(HAPI.Room));
                }
            }
        }
    }
}

